<template>
    <div>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed finibus ultricies felis eu lobortis. Mauris in leo maximus, tincidunt sapien mattis, elementum felis. Phasellus mollis neque at consectetur varius. Etiam non efficitur tortor. Cras a augue quis ante aliquam laoreet id at nunc. Ut id dui pretium dui facilisis viverra. Vestibulum ultrices dictum ipsum, ac ultrices risus placerat in. Vivamus semper neque at lectus bibendum, vel dictum ante sagittis. Morbi sodales nulla sit amet hendrerit cursus. In sit amet tortor hendrerit, mollis augue semper, mollis nulla.</p>

    <p>Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Aenean lacus nisi, porttitor id elit quis, volutpat tempor tortor. Nullam at dui blandit, aliquet urna sit amet, ullamcorper lacus. Nam nec tincidunt urna. Ut eget quam eget mauris maximus cursus. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Integer efficitur, mi sollicitudin finibus lacinia, nisl nisl consequat dolor, non consequat urna neque facilisis quam. Praesent ornare aliquet laoreet. Nulla scelerisque ex vitae dictum iaculis. Etiam euismod, ante et ullamcorper finibus, orci orci ullamcorper mi, vitae laoreet quam orci non tellus. Suspendisse mattis quam at augue pellentesque commodo. Nam ipsum augue, congue id augue eu, tincidunt consectetur dolor. Aliquam laoreet ultrices eros sit amet luctus. Quisque non diam non enim consectetur interdum quis fermentum elit. Ut sit amet pretium erat. Vestibulum eleifend aliquam lorem sed ullamcorper.</p>

    <p>Sed venenatis erat in dictum dignissim. Etiam fermentum convallis felis, nec dictum magna maximus in. Maecenas euismod consectetur arcu, vel tempus tellus convallis id. In malesuada mattis luctus. Nulla blandit erat et porttitor ultrices. Aliquam dignissim dolor eu interdum eleifend. Praesent egestas iaculis fringilla. Fusce euismod et ipsum ac laoreet.</p>

    <p>Aenean non blandit justo. Cras ac feugiat enim, in accumsan lorem. Phasellus turpis lacus, dapibus ut libero ut, lobortis fringilla ex. Quisque dapibus tristique mi. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis facilisis finibus ante. Aliquam at diam venenatis, commodo leo sit amet, aliquam eros. Nam nisl dolor, malesuada ac eros vitae, faucibus consequat urna. In aliquam a turpis id pretium. Nam et sapien ligula. Nullam facilisis, neque id venenatis vestibulum, leo risus pharetra ipsum, maximus hendrerit mi libero at libero. Donec in quam id sem ornare elementum. Donec rutrum ex id diam pellentesque, sed consectetur odio sollicitudin. Quisque interdum dictum auctor. Morbi eu augue sed nunc aliquet dignissim at sed felis. Nulla facilisi.</p>

    <p>Nulla vehicula, diam eget rutrum cursus, risus lorem efficitur arcu, a semper tellus nunc vel ipsum. Nulla at maximus arcu, et suscipit odio. Proin consequat nulla mauris. Aliquam convallis elit vel nisl fringilla pretium. Pellentesque congue nisi at sagittis vulputate. Pellentesque a libero quis erat convallis laoreet vitae in leo. Duis elit lorem, aliquam a nunc sed, malesuada suscipit massa. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Vestibulum eget dui mauris. Suspendisse potenti. Suspendisse sed blandit lectus. Sed ac quam velit.</p>

    <p>Curabitur erat turpis, tempus quis vestibulum et, commodo nec dolor. Nullam at ligula ut nisl volutpat interdum. Pellentesque finibus mauris porttitor, interdum nulla eget, scelerisque mi. Suspendisse leo eros, feugiat nec laoreet et, cursus iaculis nulla. Mauris nec erat tortor. Etiam aliquet urna at ante vestibulum, in facilisis urna ornare. Phasellus venenatis purus et dictum lobortis. In nunc erat, ornare ac rutrum vel, suscipit a lorem. Aliquam nibh lectus, scelerisque quis convallis sed, euismod eu purus. Nullam ultrices neque ut augue interdum tempor. Sed varius ullamcorper ullamcorper. Cras ac scelerisque libero, non blandit sem. Aenean non orci ut nibh accumsan ultricies at ac metus.</p>

    <p>Ut pharetra ex lorem, ut tristique est ullamcorper vitae. Ut euismod efficitur odio, nec egestas turpis eleifend a. Nulla facilisi. Nulla non diam eget velit vulputate sagittis. Vivamus pharetra lobortis justo, eu mattis est sollicitudin sit amet. Aliquam feugiat nisi ac tellus malesuada, id semper ipsum lobortis. Aliquam erat volutpat. Cras tincidunt tempor nisi, non commodo risus vestibulum in. Proin rutrum diam a orci consectetur, quis tempus nibh fermentum.</p>

    <p>Nam lacinia dolor diam, gravida elementum sem efficitur a. Curabitur quis tempor elit. Ut ut lectus et diam dignissim facilisis. Praesent gravida mollis mi. Quisque congue leo eget nulla sagittis, non aliquet nisl dapibus. Proin finibus dolor eget varius accumsan. Donec bibendum purus ut lacus eleifend, nec consequat diam fermentum. Pellentesque ac arcu nunc. Vestibulum elit tellus, pulvinar id volutpat sed, malesuada sit amet leo. Mauris quis mattis libero. Aliquam in nunc ornare, sagittis arcu at, venenatis nisi. Fusce congue urna non dui semper faucibus.</p>

    <p>Aliquam erat volutpat. Morbi eu blandit augue, quis semper lacus. Duis ultrices blandit tortor, vel aliquet lacus convallis vel. Phasellus imperdiet erat sit amet molestie aliquet. Cras imperdiet odio vitae mattis bibendum. Ut nisi orci, condimentum sodales convallis vitae, luctus eu lacus. Etiam ultrices orci at enim eleifend, vel commodo quam sollicitudin. Etiam imperdiet risus dolor. Sed consectetur id lorem in dictum.</p>

    <p>Sed lacus magna, interdum ac purus a, dignissim placerat dui. Vestibulum pretium risus vitae scelerisque laoreet. Donec a volutpat urna. Donec urna lectus, tempor eu finibus tincidunt, sollicitudin faucibus sem. Morbi et faucibus sapien. Nulla ullamcorper felis sit amet magna tempus aliquam. Suspendisse nec felis sed ligula pulvinar tristique nec quis ipsum. Vestibulum cursus malesuada quam. Nunc mauris lorem, tempus a purus eget, rutrum varius urna. Suspendisse facilisis metus metus, sit amet luctus tortor mollis vitae. Morbi semper turpis non ante consequat volutpat vel ut mi. Donec vitae dui dignissim, dignissim lorem quis, blandit nisi. Maecenas viverra diam vitae neque vehicula varius.</p>

    <p>Praesent consequat mattis magna aliquet rhoncus. Nullam quis erat odio. Praesent luctus pellentesque turpis in tempor. Curabitur ac condimentum purus. Maecenas elementum, lorem eu accumsan rutrum, massa ipsum luctus nisi, eu varius odio mi ac lectus. Praesent aliquet a massa sollicitudin dictum. Morbi ac libero eget risus pellentesque molestie quis ut est. Sed a ipsum sit amet enim sollicitudin tristique eget nec quam. Etiam a ipsum et massa facilisis commodo. Ut lacinia nisi vel diam sagittis tincidunt. Praesent in congue elit. Donec turpis risus, interdum ut pharetra eu, pellentesque in enim. Vestibulum dapibus dui at magna imperdiet semper. Praesent pellentesque, massa elementum venenatis fermentum, libero nisl scelerisque justo, et maximus velit metus vitae leo.</p>

    <p>Aenean egestas lorem massa, tempor ultrices ante luctus sit amet. Nulla scelerisque nisl tellus, eget pulvinar urna aliquam maximus. Mauris dictum ipsum sed lectus suscipit, pretium venenatis augue mollis. Suspendisse rhoncus commodo nulla, vel tincidunt ex hendrerit tempus. Ut quam lacus, volutpat sed porta ut, aliquet et est. Integer finibus metus in mauris aliquam, ut auctor metus semper. Curabitur iaculis ipsum in nisi mollis eleifend. Sed a ultrices mi.</p>

    <p>Donec tempus eleifend congue. Praesent vestibulum velit massa, nec elementum est maximus interdum. Aenean in urna convallis, tempor magna at, ultricies ligula. Vivamus suscipit odio eu eros vestibulum placerat. Nulla facilisi. Etiam congue nisi at neque vehicula rhoncus. Phasellus quis lobortis metus. Nam fringilla, libero eu elementum porttitor, quam tellus porta risus, in dignissim ante tortor eget ex. Vestibulum accumsan, turpis bibendum elementum tincidunt, magna sem placerat enim, eget pretium nisl mauris ac ipsum. Pellentesque pharetra neque in orci semper elementum.</p>

    <p>Quisque quis tortor eget est dapibus pulvinar vel a massa. Proin convallis egestas gravida. Proin ullamcorper sit amet mi vel mollis. Fusce massa neque, pretium consectetur lorem id, pretium condimentum elit. Praesent hendrerit ante lacus, congue accumsan ante interdum in. Praesent malesuada tristique vulputate. Nam elementum condimentum lacus, ac commodo ligula.</p>

    <p>Suspendisse potenti. Praesent fermentum a lorem nec tempus. Morbi arcu ex, gravida vitae blandit ut, viverra nec lacus. Cras lectus ex, efficitur id tincidunt nec, mollis eu est. Pellentesque sagittis arcu et dui molestie cursus. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Etiam at odio metus. In sed turpis nulla. Praesent quis ullamcorper velit.</p>
    </div>
</template>

<style scoped>
    div {
        text-wrap: pretty;
    }
</style>